list = []
f1 = input("Enter 1st fruit:")
list.append(f1)
f2 = input("Enter 2nd fruit:")
list.append(f2)
f3 = input("Enter 3rd fruit:")
list.append(f3)
f4 = input("Enter 4th fruit:")
list.append(f4)
f5 = input("Enter 5th fruit:")
list.append(f5)
f6 = input("Enter 6th fruit:")
list.append(f6)
f7 = input("Enter 7th fruit:")
list.append(f7)
print(list)