s = set()

n = int(input("Enter 1st number :"))
s.add(int(n))
n = int(input("Enter 2st number :"))
s.add(int(n))
n = int(input("Enter 3st number :"))
s.add(int(n))
n = int(input("Enter 4st number :"))
s.add(int(n))
n = int(input("Enter 5st number :"))
s.add(int(n))
n = int(input("Enter 6st number :"))
s.add(int(n))
n = int(input("Enter 7st number :"))
s.add(int(n))
n = int(input("Enter 8st number :"))
s.add(int(n))

print(s)